### ISSUE TITLE
IMDB & RT rating in summary no longer works (1.0.1 & 1.0.2)

### ISSUE THREAD

**Issue by Fyx0z** [piplongrun/OpenMovieDatabase.bundle#14]
Hey guys,

sorry to open up another ticket but I think the recent Plex Media Server updates (1.0.1 & 1.0.2) destroyed the "Add IMDB & Rotten Tomatoes rating to summary" functionality again. Can you guys take a look and see what caused this? I haven't changed my setup from the prior ticket. Thanks guys!

**Comment by karacaozan** [comment]
Hi, 
I had the same issue, I guess with the new version movie object has been updated and there is an issue with the plugin updating the actors list. (I saw that in the logs) Once I unchecked Actors in Plug in settings it started working again. Until a new version is published, you may want to disable actors. Hope this helps,

**Comment by jaminroe** [comment]
Not working on 1.0.3 as well 😦

**Comment by piplongrun** [comment]
I don't any errors, it's working as expected:

![x](https://cloud.githubusercontent.com/assets/453429/20949084/dc155ee4-bc17-11e6-8134-39dcb757fff5.jpg)

Make sure you have the Open Movie Database agent at the top of the list with agent:

![agent](https://cloud.githubusercontent.com/assets/453429/20949126/12b6f296-bc18-11e6-805a-886109c9c83f.jpg)

**Comment by piplongrun** [comment]
> I guess with the new version movie object has been updated and there is an issue with the plugin updating the actors list.

Correct, but this has been fixed on June 21st (
https://github.com/piplongrun/OpenMovieDatabase.bundle/commit/fb2c33aa9769b434b1d5a02dabcef60fd7cef441)
