### ISSUE TITLE
Show both RT Critic and Audience Scores

### ISSUE THREAD

**Issue by MrTemple** [piplongrun/OpenMovieDatabase.bundle#18]
When you have the Plex Movie agent pull ratings from Rotten Tomatoes, it will grab both the critic score (tomatometer) and the audience score. Plex web interface (and other clients like AppleTV app) will show both ratings.

**Why Both?**

It's really valuable to see both. Consider the following movies:

Movie | Critic Rating | Audience Rating
:- | :-: | :-:
Logan (2017) | 93% | 90%
All is Lost (2013) | 94% | 63%
Insidious (2010) | 65% | 62%
Collateral Beauty (2016) | 14% | 64%
Fantastic Four (2015) | 9% | 18%

Critics generally tend older and more arty/film-savy, while the audience tends younger and more entertainment-focused.

When both agree it's telling for sure. But when there's a disagreement, how that disagreement differs will tell you a lot about the movie. Like 'All is Lost' the 'watch Robert Redford on a sailboat for two hours' movie. It was well done, well crafted, critics loved it. But a lot of the general audience found it not so entertaining.

Similar when critics hate a movie, but audiences enjoy it okay. Collateral Beauty got savaged by critics, but quite a number of people enjoy it.

And you'll also be able to to tell a little bit more because the audience is the group of people who chose to watch the movie.  The audience for the latest Fantastic Four is very different from the audience for say, All Is Lost. They're going to be a lot more forgiving of 'artistic' problems with that sort of super-hero movie, but that audience STILL hated the movie. Super telling.

**How to Add Both**

The Plex DB has support for both RT critic and audience ratings. Here's how:

Everything is in the metadata_items table.

Critic rating is obviously stored under "rating" field. And audience rating is obviously stored under "audience_rating" field. 

But for the Rotten Tomatoes rating to appear in the Plex web/client interface you have to add the following to the "extra_data" field:

If the audience rating is 60% or greater, the "upright" popcorn image is displayed:
`at%3AaudienceRatingImage=rottentomatoes%3A%2F%2Fimage%2Erating%2Eupright`

If the audience rating is less than 60%, the "spilled" popcorn image is displayed:
`at%3AaudienceRatingImage=rottentomatoes%3A%2F%2Fimage%2Erating%2Espilled`

I've only seen this data added to the start of the values in the "extra_data" field (separated with &), so that it reads something like:

`at%3AaudienceRatingImage=rottentomatoes%3A%2F%2Fimage%2Erating%2Espilled&at%3AratingImage=rottentomatoes%3A%2F%2Fimage%2Erating%2Eripe&ex%3AhasPremiumExtras=1&ex%3AhasPremiumPrimaryExtra=1&ex%3AprimaryExtraKey=%2Flibrary%2Fmetadata%2F45568&ma%3AchapterSource=mixed`

Once again, to see an example, fetch some RT ratings with the Plex Movie agent.

**Comment by piplongrun** [comment]
Unfortunately the OMDB api is giving me the Critic Rating only, there is not more data.
